--Create table

CREATE TABLE COUNTRY(
    COUNTRY_I INT IDENTITY (1, 1),
    NAME VARCHAR(MAX),
    COUNTRY_CODE VARCHAR(MAX),
    POPULATION NUMERIC,
    CRTE_TS DATETIME NULL default CURRENT_TIMESTAMP
);